spring:
  cloud:
    config:
      server: 
        git: 
         uri: https://github.com/Stram-Developers/config-server.git
         search-paths: 
          - main

server:
  port: 8888
             
